services:
  db_webauthn:
    image: postgres:latest
    environment:
      POSTGRES_DB: webauthn
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - db_webauthn
    
volumes:
  postgres_data:
    external: true