jobs:
  - template: check-for-changes-template.yml
    parameters:
      folder: frontend
      dependencyVariableName: FrontendChanged
      jobName: CheckFrontendChanges
  - job: BuildFrontend
    displayName: 'Build Frontend'
    dependsOn: CheckFrontendChanges
    condition: eq(dependencies.CheckFrontendChanges.outputs['CheckForChanges.FrontendChanged'], 'true')
    variables:
      API_URL: 'https://api.thelogin.xyz'
    steps:
      - task: UseNode@1
        inputs:
          version: '21.x'
      - task: Cache@2
        inputs:
          # package-lock.json content is hashed to construct the key
          key: 'npm | "$(Agent.OS)" | frontend/package-lock.json'
          path: 'frontend/node_modules'
      - script: |
          pushd frontend
          echo "API URL: $VITE_API_URL"
          echo "deps: $(dependencies.CheckFrontendChanges.outputs['CheckForChanges.FrontendChanged'])"
          npm install
          npm run build
          popd
        displayName: 'Build frontend'
        env:
          VITE_API_URL: $(API_URL)
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'frontend/dist'
          artifact: 'frontend_build'
