trigger:
  batch: true # combine multiple commits or pushes to the same branch into one build
  branches:
    include:
      - main
  tags:
    include:
      - '*'
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'
  workspace:
    clean: all # delete all files before a new build

stages:
  - stage: Build
    jobs:
      - template: build-frontend-template.yml
      - template: build-backend-template.yml

  - stage: Deploy
    dependsOn: Build
    jobs:
      - template: deploy-frontend-template.yml
      - template: deploy-backend-template.yml
